'use strict';
exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('observances').del()
    .then(function () {
      // Inserts seed entries
      return knex('observances').insert([
        {
          id: 1,
          user_id: 1,
          name: 'Hari Kunzru (author), born 1969',
          color: '#95A9A2',
          picture: './img/authors/harikunzru.jpg',
          day_of: new Date ('1969-01-01'),
          is_annual: true,
          art_override: false,
          music_override: false,
          override_content: null,
          created_at: new Date('2017-07-20T13:44:00.000Z'),
          updated_at: new Date('2017-07-20T13:44:00.000Z')
        },
        {
          id: 2,
          user_id: 1,
          name: 'Umberto Eco (author), born 1932',
          color: '#013800',
          picture: './img/authors/umbertoeco.jpg',
          day_of: new Date ('1932-01-05'),
          is_annual: true,
          art_override: false,
          music_override: false,
          override_content: null,
          created_at: new Date('2017-07-20T13:44:00.000Z'),
          updated_at: new Date('2017-07-20T13:44:00.000Z')
        },
        {
          id: 3,
          user_id: 1,
          name: 'Myra Melford (pianist/composer), born 1957',
          color: '#772700',
          picture: './img/musicians/myramelford.jpg',
          day_of: new Date ('1957-01-05'),
          is_annual: true,
          art_override: false,
          music_override: true,
          override_content: {
            "sources": "[ 'bandcamp', 'bandcamp', 'bandcamp', 'bandcamp', 'bandcamp', 'bandcamp', 'bandcamp' ]",
            "src_strings": "[ 'http://bandcamp.com/EmbeddedPlayer/album=513818594/size=large/bgcol=ffffff/linkcol=0687f5/tracklist=false/transparent=true/', 'https://bandcamp.com/EmbeddedPlayer/album=1047124071/size=large/bgcol=ffffff/linkcol=0687f5/tracklist=false/transparent=true/', 'http://bandcamp.com/EmbeddedPlayer/album=2248117061/size=large/bgcol=ffffff/linkcol=0687f5/tracklist=false/transparent=true/', 'https://bandcamp.com/EmbeddedPlayer/album=24344286/size=large/bgcol=ffffff/linkcol=0687f5/tracklist=false/transparent=true/', 'https://bandcamp.com/EmbeddedPlayer/album=3367370805/size=large/bgcol=ffffff/linkcol=0687f5/tracklist=false/transparent=true/', 'https://bandcamp.com/EmbeddedPlayer/album=115737162/size=large/bgcol=ffffff/linkcol=0687f5/tracklist=false/transparent=true/', 'https://bandcamp.com/EmbeddedPlayer/album=3815170227/size=large/bgcol=ffffff/linkcol=0687f5/tracklist=false/transparent=true/' ]",
            "href_strings": "[ 'http://firehouse12records.com/album/life-carries-me-this-way', 'http://myramelford.bandcamp.com/album/myra-melford-live-at-the-stone-ep', 'http://firehouse12records.com/album/the-whole-tree-gone', 'http://kalmanovitch.bandcamp.com/album/heart-mountain-myra-melford-tanya-kalmanovitch', 'http://stevenlugerner.bandcamp.com/album/for-we-have-heard-2', 'http://stevenlugerner.bandcamp.com/album/these-are-the-words', 'http://babel-label.bandcamp.com/album/big-air' ]",
            "a_strings": "[ 'Life Carries Me This Way by Myra Melford', 'Myra Melford Live at The Stone EP by Myra Melford', 'The Whole Tree Gone by Myra Melford\'s Be Bread', 'Heart Mountain // Myra Melford + Tanya Kalmanovitch by Myra Melford and Tanya Kalmanovitch', 'For We Have Heard by Steven Lugerner, Darren Johnston, Myra Melford, Matt Wilson', 'These Are The Words by Steven Lugerner, Darren Johnston, Myra Melford, Matt Wilson', 'BIG AIR by CHRIS BATCHELOR &amp; STEVE BUCKLEY &amp; MYRA MELFORD &amp; OREN MARSHALL &amp; JIM BLACK' ]"
          },
          created_at: new Date('2017-07-20T13:44:00.000Z'),
          updated_at: new Date('2017-07-20T13:44:00.000Z')
        },
        {
          id: 4,
          user_id: 1,
          name: 'Paul Dresher (guitarist/composer), born 1951',
          color: '#FFFED6',
          picture: './img/musicians/pauldresher.jpg',
          day_of: new Date ('1951-01-08'),
          is_annual: true,
          art_override: false,
          music_override: true,
          override_content: {
            "sources": "[ 'bandcamp', 'bandcamp', 'bandcamp', 'bandcamp', 'bandcamp', 'bandcamp', 'bandcamp', 'bandcamp', 'bandcamp', 'bandcamp', 'bandcamp', 'bandcamp' ]",
            "src_strings": "[ 'https://bandcamp.com/EmbeddedPlayer/album=3898641133/size=large/bgcol=ffffff/linkcol=0687f5/tracklist=false/transparent=true/', 'https://bandcamp.com/EmbeddedPlayer/album=3832029168/size=large/bgcol=ffffff/linkcol=0687f5/tracklist=false/transparent=true/', 'https://bandcamp.com/EmbeddedPlayer/album=4097795533/size=large/bgcol=ffffff/linkcol=0687f5/tracklist=false/transparent=true/', 'https://bandcamp.com/EmbeddedPlayer/album=1819061201/size=large/bgcol=ffffff/linkcol=0687f5/tracklist=false/transparent=true/', 'https://bandcamp.com/EmbeddedPlayer/album=349671626/size=large/bgcol=ffffff/linkcol=0687f5/tracklist=false/transparent=true/', 'https://bandcamp.com/EmbeddedPlayer/album=2501753800/size=large/bgcol=ffffff/linkcol=0687f5/tracklist=false/transparent=true/', 'https://bandcamp.com/EmbeddedPlayer/album=3388073217/size=large/bgcol=ffffff/linkcol=0687f5/tracklist=false/transparent=true/', 'https://bandcamp.com/EmbeddedPlayer/album=1869433139/size=large/bgcol=ffffff/linkcol=0687f5/tracklist=false/transparent=true/', 'https://bandcamp.com/EmbeddedPlayer/album=1635723857/size=large/bgcol=ffffff/linkcol=0687f5/tracklist=false/transparent=true/', 'https://bandcamp.com/EmbeddedPlayer/album=2083774422/size=large/bgcol=ffffff/linkcol=0687f5/tracklist=false/transparent=true/', 'https://bandcamp.com/EmbeddedPlayer/album=478099629/size=large/bgcol=ffffff/linkcol=0687f5/tracklist=false/transparent=true/', 'https://bandcamp.com/EmbeddedPlayer/album=910320182/size=large/bgcol=ffffff/linkcol=0687f5/tracklist=false/transparent=true/' ]",
            "href_strings": "[ 'http://minmax.bandcamp.com/album/slipping-glimpse', 'http://minmax.bandcamp.com/album/the-tyrant-cd', 'http://minmax.bandcamp.com/album/light-moves', 'http://minmax.bandcamp.com/album/dark-blue-circumstance', 'http://minmax.bandcamp.com/album/sound-stage', 'http://minmax.bandcamp.com/album/the-gates', 'http://minmax.bandcamp.com/album/banana-humberto', 'http://minmax.bandcamp.com/album/opposites-attract', 'http://minmax.bandcamp.com/album/pioneer', 'http://minmax.bandcamp.com/album/slow-fire', 'http://minmax.bandcamp.com/album/this-same-temple', 'http://minmax.bandcamp.com/album/power-failure' ]",
            "a_strings": "[ 'Slipping Glimpse by music composed by Paul Dresher', 'The Tyrant CD by Paul Dresher, John Duykers (tenor)', 'Light Moves by music composed by Paul Dresher', 'Dark Blue Circumstance by Paul Dresher Ensemble', 'Sound Stage by Conceived and Composed by Paul Dresher', 'The Gates by composed by Paul Dresher', 'Banana Humberto by Terry Riley with the Paul Dresher Ensemble', 'Opposites Attract by Paul Dresher &amp; Ned Rothenberg', 'Pioneer by Paul Dresher', 'Slow Fire by Paul Dresher Ensemble with Rinde Eckert', 'This Same Temple by Paul Dresher Ensemble', 'Power Failure by Paul Dresher Ensemble' ]"
          },
          created_at: new Date('2017-07-20T13:44:00.000Z'),
          updated_at: new Date('2017-07-20T13:44:00.000Z')
        },
        {
          id: 5,
          user_id: 1,
          name: 'David Lang (composer), born 1957',
          color: '#2D1D27',
          picture: './img/musicians/davidlang.jpg',
          day_of: new Date ('1957-01-08'),
          is_annual: true,
          art_override: false,
          music_override: true,
          override_content: {
            "sources": "[ 'bandcamp', 'bandcamp', 'bandcamp', 'bandcamp', 'bandcamp', 'bandcamp', 'bandcamp', 'bandcamp', 'bandcamp', 'bandcamp', 'bandcamp', 'bandcamp', 'bandcamp', 'bandcamp' ]",
            "src_strings": "[ 'https://bandcamp.com/EmbeddedPlayer/album=2755599631/size=large/bgcol=ffffff/linkcol=0687f5/tracklist=false/transparent=true/', 'https://bandcamp.com/EmbeddedPlayer/track=3039488694/size=large/bgcol=ffffff/linkcol=0687f5/tracklist=false/transparent=true/', 'https://bandcamp.com/EmbeddedPlayer/album=4131036755/size=large/bgcol=ffffff/linkcol=0687f5/tracklist=false/transparent=true/', 'https://bandcamp.com/EmbeddedPlayer/track=542031401/size=large/bgcol=ffffff/linkcol=0687f5/tracklist=false/transparent=true/', 'https://bandcamp.com/EmbeddedPlayer/album=2611713493/size=large/bgcol=ffffff/linkcol=0687f5/tracklist=false/transparent=true/', 'https://bandcamp.com/EmbeddedPlayer/album=721122785/size=large/bgcol=ffffff/linkcol=0687f5/tracklist=false/transparent=true/', 'https://bandcamp.com/EmbeddedPlayer/album=3359809677/size=large/bgcol=ffffff/linkcol=0687f5/tracklist=false/transparent=true/', 'https://bandcamp.com/EmbeddedPlayer/album=1119757581/size=large/bgcol=ffffff/linkcol=0687f5/tracklist=false/transparent=true/', 'https://bandcamp.com/EmbeddedPlayer/album=1876800928/size=large/bgcol=ffffff/linkcol=0687f5/tracklist=false/transparent=true/', 'https://bandcamp.com/EmbeddedPlayer/album=2285693996/size=large/bgcol=ffffff/linkcol=0687f5/tracklist=false/transparent=true/', 'https://bandcamp.com/EmbeddedPlayer/album=377560238/size=large/bgcol=ffffff/linkcol=0687f5/tracklist=false/transparent=true/', 'https://bandcamp.com/EmbeddedPlayer/album=3300116832/size=large/bgcol=ffffff/linkcol=0687f5/tracklist=false/transparent=true/', 'https://bandcamp.com/EmbeddedPlayer/track=1764449857/size=large/bgcol=ffffff/linkcol=0687f5/tracklist=false/transparent=true/', 'https://bandcamp.com/EmbeddedPlayer/album=3969406589/size=large/bgcol=ffffff/linkcol=0687f5/tracklist=false/transparent=true/' ]",
            "href_strings": "[ 'http://davidlangmusic.bandcamp.com/album/thorn', 'http://davidlangmusic.bandcamp.com/track/forced-march', 'http://davidlangmusic.bandcamp.com/album/the-national-anthems', 'http://davidlangmusic.bandcamp.com/track/miracle-ear', 'http://davidlangmusic.bandcamp.com/album/the-difficulty-of-crossing-a-field', 'http://davidlangmusic.bandcamp.com/album/death-speaks', 'http://davidlangmusic.bandcamp.com/album/this-was-written-by-hand', 'http://davidlangmusic.bandcamp.com/album/elevated', 'http://davidlangmusic.bandcamp.com/album/love-fail', 'http://davidlangmusic.bandcamp.com/album/the-woodmans', 'http://davidlangmusic.bandcamp.com/album/child', 'http://davidlangmusic.bandcamp.com/album/the-passing-measures', 'http://davidlangmusic.bandcamp.com/track/when-we-were-children', 'http://davidlangmusic.bandcamp.com/album/untitled' ]",
            "a_strings": "[ 'thorn by Molly Barth', 'forced march by Crash Ensemble', 'the national anthems by David Lang &amp; L.A. Master Chorale', 'miracle ear by David Lang', 'the difficulty of crossing a field by David Lang, Mac Wellman, Harlem String Quartet, Beverly O&#39;Regan Thiele', 'death speaks by David Lang', 'this was written by hand by David Lang', 'elevated by David Lang', 'love fail by David Lang ft. Anonymous 4', 'The Woodmans by David Lang', 'child by David Lang', 'the passing measures by David Lang', 'when we were children by David Lang', 'Untitled by David Lang' ]"
          },
          created_at: new Date('2017-07-20T13:44:00.000Z'),
          updated_at: new Date('2017-07-20T13:44:00.000Z')
        },
        {
          id: 6,
          user_id: 1,
          name: 'Morton Feldman (composer), born 1926',
          color: '#D4D4D4',
          picture: './img/musicians/mortonfeldman.jpg',
          day_of: new Date ('1926-01-12'),
          is_annual: true,
          art_override: false,
          music_override: false,
          override_content: null,
          created_at: new Date('2017-07-20T13:44:00.000Z'),
          updated_at: new Date('2017-07-20T13:44:00.000Z')
        },
        {
          id: 7,
          user_id: 1,
          name: 'Haruki Murakami (author), born 1949',
          color: '#365CCB',
          picture: './img/authors/harukimurakami.jpg',
          day_of: new Date ('1949-01-12'),
          is_annual: true,
          art_override: false,
          music_override: false,
          override_content: null,
          created_at: new Date('2017-07-20T13:44:00.000Z'),
          updated_at: new Date('2017-07-20T13:44:00.000Z')
        },
        {
          id: 8,
          user_id: 1,
          name: 'Martin Irigoyen (guitarist/composer), born 1977',
          color: '#4FB9B4',
          picture: './img/musicians/MartinIrigoyen.jpg',
          day_of: new Date ('1977-01-14'),
          is_annual: true,
          art_override: false,
          music_override: false,
          override_content: null,
          created_at: new Date('2017-07-20T13:44:00.000Z'),
          updated_at: new Date('2017-07-20T13:44:00.000Z')
        },
        {
          id: 9,
          user_id: 1,
          name: 'Robert Filliou (artist), born 1926',
          color: '#747474',
          picture: './img/artists/RobertFilliou.jpg',
          day_of: new Date ('1926-01-17'),
          is_annual: true,
          art_override: true,
          music_override: false,
          override_content: {
            "img_paths": "[ '.img/artists/filliou01.jpg', '.img/artists/filliou02.jpg', '.img/artists/filliou03.jpg' ]",
            "titles": "[ 'Main d\'artiste', 'Raining Cats and Dogs', 'Musique télépathique n° 5' ]",
            "artists": "[ 'Robert Filliou', 'Robert Filliou', 'Robert Filliou' ]",
            "years": "[ '1967', '1969', '1978' ]"
          },
          created_at: new Date('2017-07-20T13:44:00.000Z'),
          updated_at: new Date('2017-07-20T13:44:00.000Z')
        },
        {
          id: 10,
          user_id: 1,
          name: 'Edward Feigenbaum (computer scientist), born 1936',
          color: '#B5ABAF',
          picture: './img/maths/EdwardFeigenbaum.jpg',
          day_of: new Date ('1936-01-20'),
          is_annual: true,
          art_override: false,
          music_override: false,
          override_content: null,
          created_at: new Date('2017-07-20T13:44:00.000Z'),
          updated_at: new Date('2017-07-20T13:44:00.000Z')
        },
        {
          id: 11,
          user_id: 1,
          name: 'Antonio Gramsci (communist/theorist), born 1891',
          color: '#F17D71',
          picture: './img/dissent/antoniogransci.png',
          day_of: new Date ('1891-01-22'),
          is_annual: true,
          art_override: false,
          music_override: false,
          override_content: null,
          created_at: new Date('2017-07-20T13:44:00.000Z'),
          updated_at: new Date('2017-07-20T13:44:00.000Z')
        },
        {
          id: 12,
          user_id: 1,
          name: 'John Luther Adams (composer), born 1953',
          color: '#0F89DA',
          picture: './img/musicians/johnlutheradams.jpg',
          day_of: new Date ('1953-01-23'),
          is_annual: true,
          art_override: false,
          music_override: true,
          override_content: {
            "sources": "[ 'bandcamp', 'bandcamp', 'bandcamp', 'bandcamp', 'bandcamp' ]",
            "src_strings": "[ 'https://bandcamp.com/EmbeddedPlayer/album=2951262651/size=large/bgcol=ffffff/linkcol=0687f5/tracklist=false/transparent=true/', 'https://bandcamp.com/EmbeddedPlayer/album=2278108239/size=large/bgcol=ffffff/linkcol=0687f5/tracklist=false/transparent=true/', 'https://bandcamp.com/EmbeddedPlayer/album=3225313691/size=large/bgcol=ffffff/linkcol=0687f5/tracklist=false/transparent=true/', 'https://bandcamp.com/EmbeddedPlayer/album=2594763072/size=large/bgcol=ffffff/linkcol=0687f5/tracklist=false/transparent=true/', 'https://bandcamp.com/EmbeddedPlayer/album=1247105358/size=large/bgcol=ffffff/linkcol=0687f5/tracklist=false/transparent=true/' ]",
            "href_strings": "[ 'http://johnlutheradams.bandcamp.com/album/canticles-of-the-holy-wind', 'http://johnlutheradams.bandcamp.com/album/ilimaq', 'http://johnlutheradams.bandcamp.com/album/become-ocean', 'http://johnlutheradams.bandcamp.com/album/inuksuit', 'http://johnlutheradams.bandcamp.com/album/the-mathematics-of-resonant-bodies' ]",
            "a_strings": "[ 'Canticles of the Holy Wind by John Luther Adams &amp; The Crossing', 'Ilimaq by John Luther Adams &amp; Glenn Kotche', 'Become Ocean by John Luther Adams', 'Inuksuit by John Luther Adams', 'The Mathematics of Resonant Bodies by John Luther Adams' ]"
          },
          created_at: new Date('2017-07-20T13:44:00.000Z'),
          updated_at: new Date('2017-07-20T13:44:00.000Z')
        },
        {
          id: 13,
          user_id: 1,
          name: 'Luigi Nono (composer), born 1924',
          color: '#3F3F3D',
          picture: './img/musicians/luiginono.jpg',
          day_of: new Date ('1924-01-29'),
          is_annual: true,
          art_override: false,
          music_override: false,
          override_content: null,
          created_at: new Date('2017-07-20T13:44:00.000Z'),
          updated_at: new Date('2017-07-20T13:44:00.000Z')
        },
        {
          id: 14,
          user_id: 1,
          name: 'Ahmed Abdul-Malik (bassist/oud), born 1927',
          color: '#75332E',
          picture: './img/musicians/ahmedabdulmalik.jpg',
          day_of: new Date ('1927-01-30'),
          is_annual: true,
          art_override: false,
          music_override: false,
          override_content: null,
          created_at: new Date('2017-07-20T13:44:00.000Z'),
          updated_at: new Date('2017-07-20T13:44:00.000Z')
        },
        {
          id: 15,
          user_id: 1,
          name: 'Derek Bailey (guitar), born 1930',
          color: '#747474',
          picture: './img/musicians/derekbailey.png',
          day_of: new Date ('1930-01-30'),
          is_annual: true,
          art_override: false,
          music_override: true,
          override_content: {
            "sources": "[ 'bandcamp', 'bandcamp', 'bandcamp', 'bandcamp', 'bandcamp', 'bandcamp' ]",
            "src_strings": "[ 'https://bandcamp.com/EmbeddedPlayer/album=3095361778/size=large/bgcol=ffffff/linkcol=0687f5/tracklist=false/transparent=true/', 'https://bandcamp.com/EmbeddedPlayer/album=3456138416/size=large/bgcol=ffffff/linkcol=0687f5/tracklist=false/transparent=true/', 'https://bandcamp.com/EmbeddedPlayer/album=4026532112/size=large/bgcol=ffffff/linkcol=0687f5/tracklist=false/transparent=true/', 'https://bandcamp.com/EmbeddedPlayer/album=884792575/size=large/bgcol=ffffff/linkcol=0687f5/tracklist=false/transparent=true/', 'https://bandcamp.com/EmbeddedPlayer/album=910494640/size=large/bgcol=ffffff/linkcol=0687f5/tracklist=false/transparent=true/', 'https://bandcamp.com/EmbeddedPlayer/album=3784386760/size=large/bgcol=ffffff/linkcol=0687f5/tracklist=false/transparent=true/' ]",
            "href_strings": "[ 'http://rectangle-records.bandcamp.com/album/this-guitar', 'http://scatterarchive.bandcamp.com/album/drop-me-off-at-96th', 'http://brucesfingers.bandcamp.com/album/the-complete-15th-august-2001', 'http://pantonmusic.bandcamp.com/album/derek-bailey-plus-one-music-ensemble', 'http://ictusrecords.bandcamp.com/album/drops', 'http://johnbutcher1.bandcamp.com/album/scrutables' ]",
            "a_strings": "[ 'This Guitar by Derek Bailey', 'drop me off at 96th by Derek Bailey', 'The Complete 15th August 2001 by Derek Bailey &amp; Simon H. Fell', 'Derek Bailey Plus One Music Ensemble by Derek Bailey and David Panton', 'Drops by Andrea Centazzo and Derek Bailey', 'SCRUTABLES by Derek Bailey, John Butcher &amp; Gino Robair' ]"
          },
          created_at: new Date('2017-07-20T13:44:00.000Z'),
          updated_at: new Date('2017-07-20T13:44:00.000Z')
        },
        {
          id: 16,
          user_id: 1,
          name: 'Pheeroan akLaff (drummer), born 1955',
          color: '#91A9B5',
          picture: './img/musicians/PheeroanakLaff.jpg',
          day_of: new Date ('1955-01-27'),
          is_annual: true,
          art_override: false,
          music_override: true,
          override_content: {
            "sources": "[ 'bandcamp' ]",
            "src_strings": "[ 'https://bandcamp.com/EmbeddedPlayer/album=2071939863/size=large/bgcol=ffffff/linkcol=0687f5/tracklist=false/transparent=true/' ]",
            "href_strings": "[ 'http://pheeroanaklaff.bandcamp.com/album/live-at-the-fez' ]",
            "a_strings": "[ 'Live at the Fez by Pheeroan akLaff' ]"
          },
          created_at: new Date('2017-07-20T13:44:00.000Z'),
          updated_at: new Date('2017-07-20T13:44:00.000Z')
        },
        {
          id: 17,
          user_id: 1,
          name: 'Simon H. Fell (bassist/composer), born 1959',
          color: '#E36407',
          picture: './img/musicians/simonhfell.jpg',
          day_of: new Date ('1959-01-15'),
          is_annual: true,
          art_override: false,
          music_override: true,
          override_content: {
            "sources": "[ 'bandcamp', 'bandcamp', 'bandcamp', 'bandcamp', 'bandcamp', 'bandcamp', 'bandcamp', 'bandcamp' ]",
            "src_strings": "[ 'https://bandcamp.com/EmbeddedPlayer/album=1395169973/size=large/bgcol=ffffff/linkcol=0687f5/tracklist=false/transparent=true/', 'https://bandcamp.com/EmbeddedPlayer/album=3241946996/size=large/bgcol=ffffff/linkcol=0687f5/tracklist=false/transparent=true/', 'https://bandcamp.com/EmbeddedPlayer/album=2229934290/size=large/bgcol=ffffff/linkcol=0687f5/tracklist=false/transparent=true/', 'https://bandcamp.com/EmbeddedPlayer/album=2806469424/size=large/bgcol=ffffff/linkcol=0687f5/tracklist=false/transparent=true/', 'https://bandcamp.com/EmbeddedPlayer/album=2061299384/size=large/bgcol=ffffff/linkcol=0687f5/tracklist=false/transparent=true/', 'https://bandcamp.com/EmbeddedPlayer/album=3492489609/size=large/bgcol=ffffff/linkcol=0687f5/tracklist=false/transparent=true/', 'https://bandcamp.com/EmbeddedPlayer/album=3422086435/size=large/bgcol=ffffff/linkcol=0687f5/tracklist=false/transparent=true/', 'https://bandcamp.com/EmbeddedPlayer/album=1248627216/size=large/bgcol=ffffff/linkcol=0687f5/tracklist=false/transparent=true/' ]",
            "href_strings": "[ 'http://brucesfingers.bandcamp.com/album/composition-no-125', 'http://brucesfingers.bandcamp.com/album/composition-no-30', 'http://wharffell.bandcamp.com/album/frankenstein', 'http://wharffell.bandcamp.com/album/m-m', 'http://wharffell.bandcamp.com/album/pride-and-prejudice', 'http://halliwellfell.bandcamp.com/album/9-points-in-ascent', 'http://joemorrisritiglacialeratic.bandcamp.com/album/the-necessary-and-the-possible', 'http://smithfelleisenstadt.bandcamp.com/album/k-3' ]",
            "a_strings": "[ 'Composition No. 12.5 by Simon H. Fell', 'Composition No. 30 by Simon H. Fell', 'Frankenstein by Charles Wharf / Simon H. Fell', 'M.M. by Charles Wharf / Simon H. Fell', 'Pride And Prejudice by Charles Wharf / Simon H. Fell', '9 Points In Ascent by Graham Halliwell &amp; Simon H. Fell', 'The Necessary and the Possible by Joe Morris / Alex Ward / Simon H. Fell', 'K 3 by Ian Smith / Simon H. Fell / Harris Eisenstadt' ]"
          },
          created_at: new Date('2017-07-20T13:44:00.000Z'),
          updated_at: new Date('2017-07-20T13:44:00.000Z')
        },
        {
          id: 18,
          user_id: 1,
          name: 'Luigi Dallapiccola (composer), born 1904',
          color: '#B6AA90',
          picture: './img/musicians/luigidallapiccola.jpg',
          day_of: new Date ('1904-02-03'),
          is_annual: true,
          art_override: false,
          music_override: true,
          override_content: {
            "sources": "[ 'bandcamp' ]",
            "src_strings": "[ 'https://bandcamp.com/EmbeddedPlayer/album=1168914635/size=large/bgcol=ffffff/linkcol=0687f5/tracklist=false/transparent=true/' ]",
            "href_strings": "[ 'http://jackhara.bandcamp.com/album/luigi-dallapiccola-quaderno-musicale-di-annalibera' ]",
            "a_strings": "[ 'Luigi Dallapiccola --Quaderno Musicale di Annalibera by yunichar' ]"
          },
          created_at: new Date('2017-07-20T13:44:00.000Z'),
          updated_at: new Date('2017-07-20T13:44:00.000Z')
        },
        {
          id: 19,
          user_id: 1,
          name: 'Betty Friedan (feminist/activist), born 1921',
          color: '#AF3F27',
          picture: './img/feminist/BettyFriedan.jpg',
          day_of: new Date ('1921-02-04'),
          is_annual: true,
          art_override: false,
          music_override: false,
          override_content: null,
          created_at: new Date('2017-07-20T13:44:00.000Z'),
          updated_at: new Date('2017-07-20T13:44:00.000Z')
        },
        {
          id: 20,
          user_id: 1,
          name: 'Jin-hi Kim (koto/composer), born 1957',
          color: '#F1B25B',
          picture: './img/musicians/jin-hikim.jpg',
          day_of: new Date ('1957-02-06'),
          is_annual: true,
          art_override: false,
          music_override: false,
          override_content: null,
          created_at: new Date('2017-07-20T13:44:00.000Z'),
          updated_at: new Date('2017-07-20T13:44:00.000Z')
        },
        {
          id: 21,
          user_id: 1,
          name: 'Harriet Ann Jacobs (abolitionist), born 1813',
          color: '#704F3E',
          picture: './img/dissent/JacobsHarrietAnn.jpg',
          day_of: new Date ('1813-02-11'),
          is_annual: true,
          art_override: false,
          music_override: false,
          override_content: null,
          created_at: new Date('2017-07-20T13:44:00.000Z'),
          updated_at: new Date('2017-07-20T13:44:00.000Z')
        },
        {
          id: 22,
          user_id: 1,
          name: 'Susan B. Anthony (feminist/activist), born 1820',
          color: '#F0EFEB',
          picture: './img/femminist/susanbanthony.jpg',
          day_of: new Date ('1820-02-15'),
          is_annual: true,
          art_override: false,
          music_override: false,
          override_content: null,
          created_at: new Date('2017-07-20T13:44:00.000Z'),
          updated_at: new Date('2017-07-20T13:44:00.000Z')
        },
        {
          id: 23,
          user_id: 1,
          name: 'Fred Frith (musician), born 1949',
          color: '#AAABAD',
          picture: './img/musicians/fredfrith.jpg',
          day_of: new Date ('1949-02-17'),
          is_annual: true,
          art_override: false,
          music_override: true,
          override_content: {
            "sources": "[ 'bandcamp', 'bandcamp', 'bandcamp', 'bandcamp', 'bandcamp', 'bandcamp', 'bandcamp', 'bandcamp', 'bandcamp', 'bandcamp', 'bandcamp', 'bandcamp', 'bandcamp', 'bandcamp' ]",
            "src_strings": "[ 'https://bandcamp.com/EmbeddedPlayer/album=867604907/size=large/bgcol=ffffff/linkcol=0687f5/tracklist=false/transparent=true/', 'https://bandcamp.com/EmbeddedPlayer/album=3783107360/size=large/bgcol=ffffff/linkcol=0687f5/tracklist=false/transparent=true/', 'https://bandcamp.com/EmbeddedPlayer/album=418180361/size=large/bgcol=ffffff/linkcol=0687f5/tracklist=false/transparent=true/', 'https://bandcamp.com/EmbeddedPlayer/album=1360773162/size=large/bgcol=ffffff/linkcol=0687f5/tracklist=false/transparent=true/', 'https://bandcamp.com/EmbeddedPlayer/album=279205404/size=large/bgcol=ffffff/linkcol=0687f5/tracklist=false/transparent=true/', 'https://bandcamp.com/EmbeddedPlayer/album=2602973079/size=large/bgcol=ffffff/linkcol=0687f5/tracklist=false/transparent=true/', 'https://bandcamp.com/EmbeddedPlayer/album=557862473/size=large/bgcol=ffffff/linkcol=0687f5/tracklist=false/transparent=true/', 'https://bandcamp.com/EmbeddedPlayer/album=3310471137/size=large/bgcol=ffffff/linkcol=0687f5/tracklist=false/transparent=true/', 'https://bandcamp.com/EmbeddedPlayer/album=3300632064/size=large/bgcol=ffffff/linkcol=0687f5/tracklist=false/transparent=true/', 'https://bandcamp.com/EmbeddedPlayer/album=3579696670/size=large/bgcol=ffffff/linkcol=0687f5/tracklist=false/transparent=true/', 'https://bandcamp.com/EmbeddedPlayer/album=977134657/size=large/bgcol=ffffff/linkcol=0687f5/tracklist=false/transparent=true/', 'https://bandcamp.com/EmbeddedPlayer/album=2661916816/size=large/bgcol=ffffff/linkcol=0687f5/tracklist=false/transparent=true/', 'https://bandcamp.com/EmbeddedPlayer/album=1855533683/size=large/bgcol=ffffff/linkcol=0687f5/tracklist=false/transparent=true/', 'https://bandcamp.com/EmbeddedPlayer/album=3948254235/size=large/bgcol=ffffff/linkcol=0687f5/tracklist=false/transparent=true/' ]",
            "href_strings": "[ 'http://fred-frith.bandcamp.com/album/another-day-in-fucking-paradise-24bit-44khz', 'http://fredfrith.bandcamp.com/album/impur-ii', 'http://fredfrith.bandcamp.com/album/guitar-solos', 'http://idischidiangelica.bandcamp.com/album/stone-brick-glass-wood-wire', 'http://rusconi.bandcamp.com/album/live-in-europe', 'http://intaktrec.bandcamp.com/album/backscatter-bright-blue', 'http://intaktrec.bandcamp.com/album/you-are-here', 'http://noelakchote.bandcamp.com/album/fred-frith-no-l-akchot-r-el-original-reissues-series-rectangle-1996', 'http://fredfrithandjohnbutcher.bandcamp.com/album/the-natural-order', 'http://cuneiformrecords.bandcamp.com/album/friends-enemies', 'http://rectangle-records.bandcamp.com/album/r-el', 'http://toychestra.bandcamp.com/album/what-leave-behind', 'http://skrecords.bandcamp.com/album/what-leave-behind-concerto-for-electric-guitar-and-toy-orchestra', 'http://bobostertag.bandcamp.com/album/voice-of-america' ]",
            "a_strings": "[ 'Another Day in Fucking Paradise (24bit - 44khz) by Fred Frith Trio', 'Impur II by Fred Frith', 'Guitar Solos by Fred Frith', 'Stone, Brick, Glass, Wood, Wire by Fred Frith', 'Live in Europe by RUSCONI + FRED FRITH', 'Backscatter Bright Blue by Fred Frith, Barry Guy', 'you are here by Fred Frith – Hans Koch', 'Fred Frith &amp; Noël Akchoté - Réel – (Original Reissues Series – Rectangle 1996) by Fred Frith, Noël Akchoté,', 'The Natural Order by Fred Frith and John Butcher', 'friends &amp; enemies by Fred Frith &amp; Henry Kaiser', 'Réel by Fred Frith &amp; Noël Akchoté', 'What Leave Behind by Toychestra and Fred Frith', 'What Leave Behind- Concerto for Electric Guitar and Toy Orchestra by Toychestra And Fred Frith', 'Voice of America by Fred Frith, Bob Ostertag, Phil Minton' ]"
          },
          created_at: new Date('2017-07-20T13:44:00.000Z'),
          updated_at: new Date('2017-07-20T13:44:00.000Z')
        },
        {
          id: 24,
          user_id: 1,
          name: 'Andre Norton (author), born 1912',
          color: '#6F7068',
          picture: './img/authors/andrenorton.jpeg',
          day_of: new Date ('1912-02-17'),
          is_annual: true,
          art_override: false,
          music_override: false,
          override_content: null,
          created_at: new Date('2017-07-20T13:44:00.000Z'),
          updated_at: new Date('2017-07-20T13:44:00.000Z')
        },
        {
          id: 25,
          user_id: 1,
          name: 'Anthony Davis (pianist/composer), born 1951',
          color: '#D06209',
          picture: './img/musicians/anthonydavis.jpg',
          day_of: new Date ('1951-02-20'),
          is_annual: true,
          art_override: false,
          music_override: false,
          override_content: null,
          created_at: new Date('2017-07-20T13:44:00.000Z'),
          updated_at: new Date('2017-07-20T13:44:00.000Z')
        },
        {
          id: 26,
          user_id: 1,
          name: 'Lejaren Hiller (composer), born 1924',
          color: '#8F8F8F',
          picture: './img/musicians/lejarenhiller.jpg',
          day_of: new Date ('1924-02-23'),
          is_annual: true,
          art_override: false,
          music_override: false,
          override_content: null,
          created_at: new Date('2017-07-20T13:44:00.000Z'),
          updated_at: new Date('2017-07-20T13:44:00.000Z')
        },
        {
          id: 27,
          user_id: 1,
          name: 'Monte Irvin (outfielder), born 1919',
          color: '#9C8D62',
          picture: './img/baseball/monteirvin.jpg',
          day_of: new Date ('1919-02-25'),
          is_annual: true,
          art_override: false,
          music_override: false,
          override_content: null,
          created_at: new Date('2017-07-20T13:44:00.000Z'),
          updated_at: new Date('2017-07-20T13:44:00.000Z')
        },
        {
          id: 28,
          user_id: 1,
          name: 'Pete (Grover) Cleveland (pitcher), born 1887',
          color: '#BBB9AC',
          picture: './img/baseball/petealexander.jpg',
          day_of: new Date ('1887-02-26'),
          is_annual: true,
          art_override: false,
          music_override: false,
          override_content: null,
          created_at: new Date('2017-07-20T13:44:00.000Z'),
          updated_at: new Date('2017-07-20T13:44:00.000Z')
        },
        {
          id: 29,
          user_id: 1,
          name: 'Dexter Gordon (saxophonist), born 1923',
          color: '#7F5A54',
          picture: './img/musicians/dextergordon.jpg',
          day_of: new Date ('1923-02-27'),
          is_annual: true,
          art_override: false,
          music_override: true,
          override_content: {
            "sources": "[ 'bandcamp' ]",
            "src_strings": "[ 'https://bandcamp.com/EmbeddedPlayer/album=4193897739/size=large/bgcol=ffffff/linkcol=0687f5/tracklist=false/transparent=true/' ]",
            "href_strings": "[ 'http://futuramarge.bandcamp.com/album/parisian-concert' ]",
            "a_strings": "[ 'Parisian Concert by Sonny Grey, Dexter Gordon, Georges Arvanitas Trio' ]"
          },
          created_at: new Date('2017-07-20T13:44:00.000Z'),
          updated_at: new Date('2017-07-20T13:44:00.000Z')
        },
        {
          id: 30,
          user_id: 1,
          name: 'Philip Glass (composer), born 1937',
          color: '#BEBEBE',
          picture: './img/musicians/philipglass.jpg',
          day_of: new Date ('1937-01-31'),
          is_annual: true,
          art_override: false,
          music_override: true,
          override_content: {
            "sources": "[ 'bandcamp', 'bandcamp' ]",
            "src_strings": "[ 'https://bandcamp.com/EmbeddedPlayer/album=2603088573/size=large/bgcol=ffffff/linkcol=0687f5/tracklist=false/transparent=true/', 'https://bandcamp.com/EmbeddedPlayer/album=2845177833/size=large/bgcol=ffffff/linkcol=0687f5/tracklist=false/transparent=true/' ]",
            "href_strings": "[ 'http://onisakti.bandcamp.com/album/oni-sakti-plays-philip-glass', 'http://theelectricstrings.bandcamp.com/album/string-quartet-3-mishima-by-philip-glass' ]",
            "a_strings": "[ 'Oni Sakti Plays Philip Glass by Oni Sakti', 'String Quartet #3 &quot;Mishima&quot; by Philip Glass by The Electric Strings' ]"
          },
          created_at: new Date('2017-07-20T13:44:00.000Z'),
          updated_at: new Date('2017-07-20T13:44:00.000Z')
        },
        {
          id: 31,
          user_id: 1,
          name: 'Yoko Ono (musician/activist/artist), born 1933',
          color: '#C5A590',
          picture: './img/musicians/yokoono.jpg',
          day_of: new Date ('1933-02-18'),
          is_annual: true,
          art_override: true,
          music_override: true,
          override_content: {
            "img_paths": "[ './img/artists/ono01.jpg', './img/artists/ono02.jpg', './img/artists/ono03.jpg', './img/artists/ono04.jpg', './img/artists/ono05.jpg', './img/artists/ono06.jpg', './img/artists/ono07.jpg', './img/artists/ono08.jpg', './img/artists/ono09.jpg', './img/artists/ono10.jpg' ]",
            "titles": "[ 'Touch Poem #5', 'Painting To Be Stepped On', 'Bag Piece', 'Cut Piece', 'Apple', 'Ceiling Painting', 'Painting To Hammer A Nail', 'Danger Box', 'Waterdrop Painting (Version 1)', 'Half-a-Room' ]",
            "artists": "[ 'Yoko Ono', 'Yoko Ono', 'Yoko Ono', 'Yoko Ono', 'Yoko Ono', 'Yoko Ono', 'Yoko Ono', 'Yoko Ono', 'Yoko Ono', 'Yoko Ono' ]",
            "years": "[ '1960', '1960', '1964', '1964', '1966', '1966', '1966', '1966', '1961-2015', '1967' ]",
            "sources": "[ 'bandcamp', 'bandcamp', 'bandcamp', 'bandcamp', 'bandcamp' ]",
            "src_strings": "[ 'https://bandcamp.com/EmbeddedPlayer/album=3128065331/size=large/bgcol=ffffff/linkcol=0687f5/tracklist=false/transparent=true/', 'https://bandcamp.com/EmbeddedPlayer/album=2396370982/size=large/bgcol=ffffff/linkcol=0687f5/tracklist=false/transparent=true/', 'https://bandcamp.com/EmbeddedPlayer/album=2178294126/size=large/bgcol=ffffff/linkcol=0687f5/tracklist=false/transparent=true/', 'https://bandcamp.com/EmbeddedPlayer/album=2683672888/size=large/bgcol=ffffff/linkcol=0687f5/tracklist=false/transparent=true/', 'https://bandcamp.com/EmbeddedPlayer/album=1437353149/size=large/bgcol=ffffff/linkcol=0687f5/tracklist=false/transparent=true/' ]",
            "href_strings": "[ 'http://yokoono.bandcamp.com/album/approximately-infinite-universe', 'http://yokoono.bandcamp.com/album/feeling-the-space', 'http://yokoono.bandcamp.com/album/plastic-ono-band', 'http://yokoono.bandcamp.com/album/unfinished-music-no-1-two-virgins', 'http://yokoono.bandcamp.com/album/unfinished-music-no-2-life-with-the-lions' ]",
            "a_strings": "[ 'Approximately Infinite Universe by Yoko Ono', 'Feeling The Space by Yoko Ono', 'Plastic Ono Band by Yoko Ono', 'Unfinished Music No. 1: Two Virgins by John Lennon/Yoko Ono', 'Unfinished Music No. 2: Life With the Lions by John Lennon/Yoko Ono' ]"
          },
          created_at: new Date('2017-07-20T13:44:00.000Z'),
          updated_at: new Date('2017-07-20T13:44:00.000Z')
        },
        {
          id: 32,
          user_id: 1,
          name: 'Elmer Gantry by Sinclair Lewis, published in 1927. Banned in Boston and other cities and denounced from pulpits accross the US.',
          color: '#E6CE6D',
          picture: './img/books/elmergantry.jpg',
          day_of: new Date ('1927-03-01'),
          is_annual: true,
          art_override: false,
          music_override: false,
          override_content: null,
          created_at: new Date('2017-07-20T13:44:00.000Z'),
          updated_at: new Date('2017-07-20T13:44:00.000Z')
        },
        {
          id: 33,
          user_id: 1,
          name: 'Marie Louise Berneri (anarchist/activist/author), born in 1918',
          color: '#949494',
          picture: './img/dissent/marielouiseberneri.jpg',
          day_of: new Date ('1918-03-01'),
          is_annual: true,
          art_override: false,
          music_override: false,
          override_content: null,
          created_at: new Date('2017-07-20T13:44:00.000Z'),
          updated_at: new Date('2017-07-20T13:44:00.000Z')
        },
        {
          id: 34,
          user_id: 1,
          name: 'John Irving (author), born in 1942',
          color: '#3A6240',
          picture: './img/authors/johnirving.jpg',
          day_of: new Date ('1942-03-02'),
          is_annual: true,
          art_override: false,
          music_override: false,
          override_content: null,
          created_at: new Date('2017-07-20T13:44:00.000Z'),
          updated_at: new Date('2017-07-20T13:44:00.000Z')
        },
        {
          id: 35,
          user_id: 1,
          name: 'Georg Cantor (mathematician), born 1845',
          color: '#2C2C2C',
          picture: './img/maths/georgcantor.jpg',
          day_of: new Date ('1845-03-03'),
          is_annual: true,
          art_override: false,
          music_override: false,
          override_content: null,
          created_at: new Date('2017-07-20T13:44:00.000Z'),
          updated_at: new Date('2017-07-20T13:44:00.000Z')
        },
        {
          id: 36,
          user_id: 1,
          name: 'Peter Brötzmann (saxophonist, free-improvisation warrior), born 1941',
          color: '#788B27',
          picture: './img/musicians/peterbrotzmann.jpg',
          day_of: new Date ('1941-03-06'),
          is_annual: true,
          art_override: false,
          music_override: true,
          override_content: {
            "sources": "[ 'bandcamp', 'bandcamp', 'bandcamp', 'bandcamp', 'bandcamp', 'bandcamp', 'bandcamp', 'bandcamp', 'bandcamp', 'bandcamp', 'bandcamp', 'bandcamp', 'bandcamp', 'bandcamp', 'bandcamp', 'bandcamp', 'bandcamp', 'bandcamp', 'bandcamp', 'bandcamp', 'bandcamp', 'bandcamp', 'bandcamp', 'bandcamp', 'bandcamp', 'bandcamp', 'bandcamp', 'bandcamp', 'bandcamp', 'bandcamp', 'bandcamp', 'bandcamp', 'bandcamp', 'bandcamp', 'bandcamp', 'bandcamp', 'bandcamp', 'bandcamp', 'bandcamp' ]",
            "src_strings": "[ 'https://bandcamp.com/EmbeddedPlayer/album=3136913313/size=large/bgcol=ffffff/linkcol=0687f5/tracklist=false/transparent=true/', 'https://bandcamp.com/EmbeddedPlayer/album=1920464073/size=large/bgcol=ffffff/linkcol=0687f5/tracklist=false/transparent=true/', 'https://bandcamp.com/EmbeddedPlayer/album=1527251499/size=large/bgcol=ffffff/linkcol=0687f5/tracklist=false/transparent=true/', 'https://bandcamp.com/EmbeddedPlayer/album=4207812824/size=large/bgcol=ffffff/linkcol=0687f5/tracklist=false/transparent=true/', 'https://bandcamp.com/EmbeddedPlayer/album=20870587/size=large/bgcol=ffffff/linkcol=0687f5/tracklist=false/transparent=true/', 'https://bandcamp.com/EmbeddedPlayer/album=215264390/size=large/bgcol=ffffff/linkcol=0687f5/tracklist=false/transparent=true/', 'https://bandcamp.com/EmbeddedPlayer/album=721391904/size=large/bgcol=ffffff/linkcol=0687f5/tracklist=false/transparent=true/', 'https://bandcamp.com/EmbeddedPlayer/album=2840445577/size=large/bgcol=ffffff/linkcol=0687f5/tracklist=false/transparent=true/', 'https://bandcamp.com/EmbeddedPlayer/album=3394077719/size=large/bgcol=ffffff/linkcol=0687f5/tracklist=false/transparent=true/', 'https://bandcamp.com/EmbeddedPlayer/album=3609676815/size=large/bgcol=ffffff/linkcol=0687f5/tracklist=false/transparent=true/', 'https://bandcamp.com/EmbeddedPlayer/album=2406739828/size=large/bgcol=ffffff/linkcol=0687f5/tracklist=false/transparent=true/', 'https://bandcamp.com/EmbeddedPlayer/album=3275928952/size=large/bgcol=ffffff/linkcol=0687f5/tracklist=false/transparent=true/', 'https://bandcamp.com/EmbeddedPlayer/album=459449773/size=large/bgcol=ffffff/linkcol=0687f5/tracklist=false/transparent=true/', 'https://bandcamp.com/EmbeddedPlayer/album=957784974/size=large/bgcol=ffffff/linkcol=0687f5/tracklist=false/transparent=true/', 'https://bandcamp.com/EmbeddedPlayer/album=4251254634/size=large/bgcol=ffffff/linkcol=0687f5/tracklist=false/transparent=true/', 'https://bandcamp.com/EmbeddedPlayer/album=42778542/size=large/bgcol=ffffff/linkcol=0687f5/tracklist=false/transparent=true/', 'https://bandcamp.com/EmbeddedPlayer/album=303998185/size=large/bgcol=ffffff/linkcol=0687f5/tracklist=false/transparent=true/', 'https://bandcamp.com/EmbeddedPlayer/album=2844875543/size=large/bgcol=ffffff/linkcol=0687f5/tracklist=false/transparent=true/', 'https://bandcamp.com/EmbeddedPlayer/album=662478280/size=large/bgcol=ffffff/linkcol=0687f5/tracklist=false/transparent=true/', 'https://bandcamp.com/EmbeddedPlayer/album=558931210/size=large/bgcol=ffffff/linkcol=0687f5/tracklist=false/transparent=true/', 'https://bandcamp.com/EmbeddedPlayer/album=2087463680/size=large/bgcol=ffffff/linkcol=0687f5/tracklist=false/transparent=true/', 'https://bandcamp.com/EmbeddedPlayer/album=4127432487/size=large/bgcol=ffffff/linkcol=0687f5/tracklist=false/transparent=true/', 'https://bandcamp.com/EmbeddedPlayer/album=2395337359/size=large/bgcol=ffffff/linkcol=0687f5/tracklist=false/transparent=true/', 'https://bandcamp.com/EmbeddedPlayer/album=3719167734/size=large/bgcol=ffffff/linkcol=0687f5/tracklist=false/transparent=true/', 'https://bandcamp.com/EmbeddedPlayer/album=2269468506/size=large/bgcol=ffffff/linkcol=0687f5/tracklist=false/transparent=true/', 'https://bandcamp.com/EmbeddedPlayer/album=1201935921/size=large/bgcol=ffffff/linkcol=0687f5/tracklist=false/transparent=true/', 'https://bandcamp.com/EmbeddedPlayer/album=791657436/size=large/bgcol=ffffff/linkcol=0687f5/tracklist=false/transparent=true/', 'https://bandcamp.com/EmbeddedPlayer/album=3630159398/size=large/bgcol=ffffff/linkcol=0687f5/tracklist=false/transparent=true/', 'https://bandcamp.com/EmbeddedPlayer/album=2207935661/size=large/bgcol=ffffff/linkcol=0687f5/tracklist=false/transparent=true/', 'https://bandcamp.com/EmbeddedPlayer/album=3042708779/size=large/bgcol=ffffff/linkcol=0687f5/tracklist=false/transparent=true/', 'https://bandcamp.com/EmbeddedPlayer/album=4146559393/size=large/bgcol=ffffff/linkcol=0687f5/tracklist=false/transparent=true/', 'https://bandcamp.com/EmbeddedPlayer/album=1097325401/size=large/bgcol=ffffff/linkcol=0687f5/tracklist=false/transparent=true/', 'https://bandcamp.com/EmbeddedPlayer/album=1800649178/size=large/bgcol=ffffff/linkcol=0687f5/tracklist=false/transparent=true/', 'https://bandcamp.com/EmbeddedPlayer/album=2774140364/size=large/bgcol=ffffff/linkcol=0687f5/tracklist=false/transparent=true/', 'https://bandcamp.com/EmbeddedPlayer/album=1721292649/size=large/bgcol=ffffff/linkcol=0687f5/tracklist=false/transparent=true/', 'https://bandcamp.com/EmbeddedPlayer/album=1338236006/size=large/bgcol=ffffff/linkcol=0687f5/tracklist=false/transparent=true/', 'https://bandcamp.com/EmbeddedPlayer/album=4112688506/size=large/bgcol=ffffff/linkcol=0687f5/tracklist=false/transparent=true/', 'https://bandcamp.com/EmbeddedPlayer/album=3574118200/size=large/bgcol=ffffff/linkcol=0687f5/tracklist=false/transparent=true/', 'https://bandcamp.com/EmbeddedPlayer/album=279329723/size=large/bgcol=ffffff/linkcol=0687f5/tracklist=false/transparent=true/' ]",
            "href_strings": "[ 'http://peterbrtzmann.bandcamp.com/album/chicago-tentet-1-3-nights-in-oslo', 'http://peterbrtzmann.bandcamp.com/album/the-chicago-octet-tentet', 'http://peterbrtzmann.bandcamp.com/album/hairy-bones-snakelust-to-kenji-nakagami', 'http://peterbrtzmann.bandcamp.com/album/ada-live-at-the-cafe-oto-with-pat-thomas', 'http://peterbrtzmann.bandcamp.com/album/ada-live-at-cafe-oto-with-steve-noble', 'http://peterbrtzmann.bandcamp.com/album/peter-br-tzmann-fred-lonberg-holm-the-brain-of-the-dog-in-section', 'http://peterbrtzmann.bandcamp.com/album/br-tzmann-swell-nilssen-love-krakow-nights', 'http://peterbrtzmann.bandcamp.com/album/br-tzmann-satoh-moriyama-yatagarasu', 'http://peterbrtzmann.bandcamp.com/album/peter-br-tzmann-j-rg-fischer-live-in-wiesbaden', 'http://peterbrtzmann.bandcamp.com/album/berg-borg-br-tz-man-n-ride-into-the-blue', 'http://peterbrtzmann.bandcamp.com/album/berg-borg-br-tz-man-n-blue-zoo', 'http://peterbrtzmann.bandcamp.com/album/br-tzmann-edwards-noble-soulfood-available', 'http://peterbrtzmann.bandcamp.com/album/ears-are-filled-with-wonder', 'http://peterbrtzmann.bandcamp.com/album/left', 'http://peterbrtzmann.bandcamp.com/album/funny-rat', 'http://peterbrtzmann.bandcamp.com/album/call-before-you-dig', 'http://peterbrtzmann.bandcamp.com/album/walk-love-sleep', 'http://peterbrtzmann.bandcamp.com/album/live-at-the-empty-bottle', 'http://peterbrtzmann.bandcamp.com/album/at-fresnes', 'http://peterbrtzmann.bandcamp.com/album/ada', 'http://peterbrtzmann.bandcamp.com/album/roma', 'http://peterbrtzmann.bandcamp.com/album/born-broke', 'http://peterbrtzmann.bandcamp.com/album/be-night-music', 'http://peterbrtzmann.bandcamp.com/album/no-one-ever-works-alone', 'http://peterbrtzmann.bandcamp.com/album/broken-english', 'http://peterbrtzmann.bandcamp.com/album/american-landscape-2', 'http://peterbrtzmann.bandcamp.com/album/images', 'http://peterbrtzmann.bandcamp.com/album/signs', 'http://peterbrtzmann.bandcamp.com/album/the-damage-is-done', 'http://peterbrtzmann.bandcamp.com/album/at-molde-2007', 'http://peterbrtzmann.bandcamp.com/album/hairy-bones', 'http://peterbrtzmann.bandcamp.com/album/american-landscapes-1', 'http://peterbrtzmann.bandcamp.com/album/black-hole', 'http://peterbrtzmann.bandcamp.com/album/medicina', 'http://peterbrtzmann.bandcamp.com/album/wels-concert', 'http://peterbrtzmann.bandcamp.com/album/the-dried-rat-dog', 'http://peterbrtzmann.bandcamp.com/album/stone-water', 'http://peterbrtzmann.bandcamp.com/album/sweetsweat', 'http://peterbrtzmann.bandcamp.com/album/the-fat-is-gone' ]",
            "a_strings": "[ 'Chicago Tentet +1: 3 Nights in Oslo by Peter Brötzmann', 'The Chicago Octet/Tentet by Peter Brötzmann', 'Hairy Bones : Snakelust (to Kenji Nakagami) by Peter Brötzmann', 'ADA: Live at the Cafe Oto with Pat Thomas by Peter Brötzmann', 'ADA: Live at Cafe Oto with Steve Noble by Peter Brötzmann', 'Peter Brötzmann &amp; Fred Lonberg-Holm: The Brain of the Dog In Section by Peter Brötzmann', 'Brötzmann Swell Nilssen-Love: Krakow Nights by Peter Brötzmann', 'Brötzmann Satoh Moriyama: Yatagarasu by Peter Brötzmann', 'Peter Brötzmann &amp; Jörg Fischer: Live In Wiesbaden by Peter Brötzmann', 'Berg Borg Brötz man/n: Ride Into The Blue by Peter Brötzmann', 'Berg Borg Brötz man/n: Blue Zoo by Peter Brötzmann', 'Brötzmann Edwards Noble: Soulfood Available by Peter Brötzmann', 'Ears Are Filled With Wonder by Peter Brötzmann', 'Left by Peter Brötzmann', 'Funny Rat by Peter Brötzmann', 'Call Before You Dig by Peter Brötzmann', 'Walk, Love, Sleep by Peter Brötzmann', 'Live at the Empty Bottle by Peter Brötzmann', 'At Fresnes by Peter Brötzmann', 'ADA by Peter Brötzmann', 'Roma by Peter Brötzmann', 'Born Broke by Peter Brötzmann', 'Be Night, Music by Peter Brötzmann', 'No One Ever Works Alone by Peter Brötzmann', 'Broken English by Peter Brötzmann', 'American Landscape 2 by Peter Brötzmann', 'Images by Peter Brötzmann', 'Signs by Peter Brötzmann', 'The Damage Is Done by Peter Brötzmann', 'at Molde 2007 by Peter Brötzmann', 'Hairy Bones by Peter Brötzmann', 'American Landscapes 1 by Peter Brötzmann', 'Black Hole by Peter Brötzmann', 'Medicina by Peter Brötzmann', 'Wels Concert by Peter Brötzmann', 'The Dried Rat-Dog by Peter Brötzmann', 'Stone / Water by Peter Brötzmann', 'Sweetsweat by Peter Brötzmann', 'The Fat Is Gone by Peter Brötzmann' ]"
          },
          created_at: new Date('2017-07-20T13:44:00.000Z'),
          updated_at: new Date('2017-07-20T13:44:00.000Z')
        },
        {
          id: 37,
          user_id: 1,
          name: 'Ornette Coleman (harmolodic guru, multi-instrumentalist, composer), born 1930',
          color: '#994942',
          picture: './img/musicians/ornettecoleman55.jpg',
          day_of: new Date ('1930-03-09'),
          is_annual: true,
          art_override: false,
          music_override: true,
          override_content: {
            "sources": "[ 'bandcamp' ]",
            "src_strings": "[ 'https://bandcamp.com/EmbeddedPlayer/album=2602402062/size=large/bgcol=ffffff/linkcol=0687f5/tracklist=false/transparent=true/' ]",
            "href_strings": "[ 'http://ornettecoleman.bandcamp.com/album/town-hall-1962' ]",
            "a_strings": "[ 'Town Hall 1962 by Ornette Coleman' ]"
          },
          created_at: new Date('2017-07-20T13:44:00.000Z'),
          updated_at: new Date('2017-07-20T13:44:00.000Z')
        },
        {
          id: 38,
          user_id: 1,
          name: 'Leroy Jenkins (violinist, improvisor, composer), born 1932',
          color: '#636363',
          picture: './img/musicians/leroyjenkins.jpg',
          day_of: new Date ('1932-03-11'),
          is_annual: true,
          art_override: false,
          music_override: false,
          override_content: null,
          created_at: new Date('2017-07-20T13:44:00.000Z'),
          updated_at: new Date('2017-07-20T13:44:00.000Z')
        },
        {
          id: 39,
          user_id: 1,
          name: 'Albert Einstein (physicist), born 1879',
          color: '#333A44',
          picture: './img/maths/alberteinstein.jpg',
          day_of: new Date ('1879-03-14'),
          is_annual: true,
          art_override: false,
          music_override: false,
          override_content: null,
          created_at: new Date('2017-07-20T13:44:00.000Z'),
          updated_at: new Date('2017-07-20T13:44:00.000Z')
        },
        {
          id: 40,
          user_id: 1,
          name: 'Ben Johnston (composer), born 1926',
          color: '#4D4B3E',
          picture: './img/musicians/benjohnston.jpg',
          day_of: new Date ('1926-03-15'),
          is_annual: true,
          art_override: false,
          music_override: false,
          override_content: null,
          created_at: new Date('2017-07-20T13:44:00.000Z'),
          updated_at: new Date('2017-07-20T13:44:00.000Z')
        },
        {
          id: 41,
          user_id: 1,
          name: 'Bill Fisell (guitarist), born 1951',
          color: '#EDF0E9',
          picture: './img/musicians/billfrisell.jpg',
          day_of: new Date ('1951-03-18'),
          is_annual: true,
          art_override: false,
          music_override: true,
          override_content: {
            "sources": "[ 'bandcamp' ]",
            "src_strings": "[ 'https://bandcamp.com/EmbeddedPlayer/album=300143193/size=large/bgcol=ffffff/linkcol=0687f5/tracklist=false/transparent=true/' ]",
            "href_strings": "[ 'http://timbernebillfrisell.bandcamp.com/album/theoretically' ]",
            "a_strings": "[ 'Theoretically by Tim Berne &amp; Bill Frisell' ]"
          },
          created_at: new Date('2017-07-20T13:44:00.000Z'),
          updated_at: new Date('2017-07-20T13:44:00.000Z')
        },
        {
          id: 42,
          user_id: 1,
          name: 'Josef Albers (artist), born 1888',
          color: '#DFDEDC',
          picture: './img/artists/josefalbers.jpg',
          day_of: new Date ('1888-03-19'),
          is_annual: true,
          art_override: true,
          music_override: false,
          override_content: {
            "img_paths": "[ './img/artists/albers01.jpg', './img/artists/albers02.jpg', './img/artists/albers03.jpg', './img/artists/albers04.jpg', './img/artists/albers05.jpg', './img/artists/albers06.jpg', './img/artists/albers07.jpg', './img/artists/albers08.jpg', './img/artists/albers09.jpg' ]",
            "titles": "[ 'Grid Mounted', 'Frontal', 'Factory', 'Park', 'Skyscrapers on Transparent Yellow', 'Piano Keys', 'Homage to the Square: Blue, White, Grey', 'Variant/Adobe: Familiar Front', 'Homage to the Square' ]",
            "artists": "[ 'Josef Albers', 'Josef Albers', 'Josef Albers', 'Josef Albers', 'Josef Albers', 'Josef Albers', 'Josef Albers', 'Josef Albers', 'Josef Albers' ]",
            "years": "[ '1921', '1927', '1925', '1924', '1929', '1932', '1951', '1948', '1967' ]"
          },
          created_at: new Date('2017-07-20T13:44:00.000Z'),
          updated_at: new Date('2017-07-20T13:44:00.000Z')
        },
        {
          id: 43,
          user_id: 1,
          name: 'Erich Fromm (theorist), born 1900',
          color: '#B24924',
          picture: './img/dissent/erichfromm.jpg',
          day_of: new Date ('1900-03-23'),
          is_annual: true,
          art_override: false,
          music_override: false,
          override_content: null,
          created_at: new Date('2017-07-20T13:44:00.000Z'),
          updated_at: new Date('2017-07-20T13:44:00.000Z')
        },
        {
          id: 44,
          user_id: 1,
          name: 'Dave Douglas (trumpet/composer), born 1963',
          color: '#515659',
          picture: './img/musicians/davedouglas.jpg',
          day_of: new Date ('1963-03-24'),
          is_annual: true,
          art_override: false,
          music_override: true,
          override_content: {
            "sources": "[ 'bandcamp', 'bandcamp', 'bandcamp', 'bandcamp', 'bandcamp', 'bandcamp', 'bandcamp', 'bandcamp', 'bandcamp', 'bandcamp', 'bandcamp', 'bandcamp', 'bandcamp', 'bandcamp', 'bandcamp', 'bandcamp', 'bandcamp', 'bandcamp', 'bandcamp', 'bandcamp', 'bandcamp', 'bandcamp', 'bandcamp', 'bandcamp', 'bandcamp', 'bandcamp', 'bandcamp', 'bandcamp', 'bandcamp' ]",
            "src_strings": "[ 'https://bandcamp.com/EmbeddedPlayer/album=4225505557/size=large/bgcol=ffffff/linkcol=0687f5/tracklist=false/transparent=true/', 'https://bandcamp.com/EmbeddedPlayer/album=2720996189/size=large/bgcol=ffffff/linkcol=0687f5/tracklist=false/transparent=true/', 'https://bandcamp.com/EmbeddedPlayer/album=1145254752/size=large/bgcol=ffffff/linkcol=0687f5/tracklist=false/transparent=true/', 'https://bandcamp.com/EmbeddedPlayer/album=3934701147/size=large/bgcol=ffffff/linkcol=0687f5/tracklist=false/transparent=true/', 'https://bandcamp.com/EmbeddedPlayer/album=336528174/size=large/bgcol=ffffff/linkcol=0687f5/tracklist=false/transparent=true/', 'https://bandcamp.com/EmbeddedPlayer/album=1373892235/size=large/bgcol=ffffff/linkcol=0687f5/tracklist=false/transparent=true/', 'https://bandcamp.com/EmbeddedPlayer/album=633647417/size=large/bgcol=ffffff/linkcol=0687f5/tracklist=false/transparent=true/', 'https://bandcamp.com/EmbeddedPlayer/album=2365773131/size=large/bgcol=ffffff/linkcol=0687f5/tracklist=false/transparent=true/', 'https://bandcamp.com/EmbeddedPlayer/album=1245526296/size=large/bgcol=ffffff/linkcol=0687f5/tracklist=false/transparent=true/', 'https://bandcamp.com/EmbeddedPlayer/album=1147086590/size=large/bgcol=ffffff/linkcol=0687f5/tracklist=false/transparent=true/', 'https://bandcamp.com/EmbeddedPlayer/album=1369607537/size=large/bgcol=ffffff/linkcol=0687f5/tracklist=false/transparent=true/', 'https://bandcamp.com/EmbeddedPlayer/album=876634885/size=large/bgcol=ffffff/linkcol=0687f5/tracklist=false/transparent=true/', 'https://bandcamp.com/EmbeddedPlayer/album=3346404060/size=large/bgcol=ffffff/linkcol=0687f5/tracklist=false/transparent=true/', 'https://bandcamp.com/EmbeddedPlayer/album=2638213155/size=large/bgcol=ffffff/linkcol=0687f5/tracklist=false/transparent=true/', 'https://bandcamp.com/EmbeddedPlayer/album=3592654121/size=large/bgcol=ffffff/linkcol=0687f5/tracklist=false/transparent=true/', 'https://bandcamp.com/EmbeddedPlayer/album=2076596001/size=large/bgcol=ffffff/linkcol=0687f5/tracklist=false/transparent=true/', 'https://bandcamp.com/EmbeddedPlayer/album=4052927237/size=large/bgcol=ffffff/linkcol=0687f5/tracklist=false/transparent=true/', 'https://bandcamp.com/EmbeddedPlayer/album=1309805024/size=large/bgcol=ffffff/linkcol=0687f5/tracklist=false/transparent=true/', 'https://bandcamp.com/EmbeddedPlayer/album=3030743066/size=large/bgcol=ffffff/linkcol=0687f5/tracklist=false/transparent=true/', 'https://bandcamp.com/EmbeddedPlayer/album=382421358/size=large/bgcol=ffffff/linkcol=0687f5/tracklist=false/transparent=true/', 'https://bandcamp.com/EmbeddedPlayer/album=3485311537/size=large/bgcol=ffffff/linkcol=0687f5/tracklist=false/transparent=true/', 'https://bandcamp.com/EmbeddedPlayer/album=2101163688/size=large/bgcol=ffffff/linkcol=0687f5/tracklist=false/transparent=true/', 'https://bandcamp.com/EmbeddedPlayer/album=329112252/size=large/bgcol=ffffff/linkcol=0687f5/tracklist=false/transparent=true/', 'https://bandcamp.com/EmbeddedPlayer/album=2879565205/size=large/bgcol=ffffff/linkcol=0687f5/tracklist=false/transparent=true/', 'https://bandcamp.com/EmbeddedPlayer/album=2362315648/size=large/bgcol=ffffff/linkcol=0687f5/tracklist=false/transparent=true/', 'https://bandcamp.com/EmbeddedPlayer/album=2468430192/size=large/bgcol=ffffff/linkcol=0687f5/tracklist=false/transparent=true/', 'https://bandcamp.com/EmbeddedPlayer/album=2984224859/size=large/bgcol=ffffff/linkcol=0687f5/tracklist=false/transparent=true/', 'https://bandcamp.com/EmbeddedPlayer/album=932561696/size=large/bgcol=ffffff/linkcol=0687f5/tracklist=false/transparent=true/', 'https://bandcamp.com/EmbeddedPlayer/album=1488764594/size=large/bgcol=ffffff/linkcol=0687f5/tracklist=false/transparent=true/' ]",
            "href_strings": "[  'http://davedouglas.bandcamp.com/album/the-new-national-anthem', 'http://davedouglas.bandcamp.com/album/metamorphosis', 'http://davedouglas.bandcamp.com/album/dada-people', 'http://davedouglas.bandcamp.com/album/dark-territory', 'http://davedouglas.bandcamp.com/album/fabliaux', 'http://davedouglas.bandcamp.com/album/brazen-heart-live-at-jazz-standard', 'http://davedouglas.bandcamp.com/album/brazen-heart', 'http://davedouglas.bandcamp.com/album/high-risk', 'http://davedouglas.bandcamp.com/album/present-joys', 'http://davedouglas.bandcamp.com/album/riverside', 'http://davedouglas.bandcamp.com/album/time-travel', 'http://davedouglas.bandcamp.com/album/be-still', 'http://davedouglas.bandcamp.com/album/meaning-and-mystery', 'http://davedouglas.bandcamp.com/album/magic-triangle-leap-of-faith', 'http://davedouglas.bandcamp.com/album/gps-volume-1-rare-metals', 'http://davedouglas.bandcamp.com/album/gps-volume-2-orange-afternoons', 'http://davedouglas.bandcamp.com/album/gps-volume-3-bad-mango', 'http://davedouglas.bandcamp.com/album/united-front', 'http://davedouglas.bandcamp.com/album/spark-of-being-box-set', 'http://davedouglas.bandcamp.com/album/on-stage', 'http://davedouglas.bandcamp.com/album/spirit-moves', 'http://davedouglas.bandcamp.com/album/live-at-jazz-standard-8-set', 'http://davedouglas.bandcamp.com/album/moonshine', 'http://davedouglas.bandcamp.com/album/live-at-the-jazz-standard-12-set', 'http://davedouglas.bandcamp.com/album/dd-50-special-edition-50th-birthday-recordings', 'http://davedouglas.bandcamp.com/album/keystone', 'http://davedouglas.bandcamp.com/album/spark-of-being-burst', 'http://davedouglas.bandcamp.com/album/spark-of-being-expand', 'http://davedouglas.bandcamp.com/album/spark-of-being-soundtrack' ]",
            "a_strings": "[ 'The New National Anthem by Riverside', 'Metamorphosis by Dave Douglas', 'Dada People by Dave Douglas &amp; Frank Woeste', 'Dark Territory by High Risk', 'Fabliaux by Dave Douglas &amp; Monash Art Ensemble', 'Brazen Heart Live at Jazz Standard by Dave Douglas Quintet 2015', 'Brazen Heart by Dave Douglas Quintet', 'High Risk by High Risk', 'Present Joys by Douglas/Caine', 'Riverside by Douglas/Doxas/Swallow/Doxas', 'Time Travel by Dave Douglas Quintet', 'Be Still by Dave Douglas Quintet', 'Meaning and Mystery by Dave Douglas Quintet', 'Magic Triangle / Leap Of Faith by Dave Douglas Quartet', 'GPS, Volume 1: Rare Metals by Dave Douglas &amp; Brass Ecstasy', 'GPS, Volume 2: Orange Afternoons by Dave Douglas', 'GPS, Volume 3: Bad Mango by Dave Douglas &amp; So Percussion', 'United Front by Dave Douglas &amp; Brass Ecstasy', 'Spark Of Being [Box Set] by Dave Douglas &amp; Keystone', 'On Stage by Dave Douglas &amp; Brass Ecstasy', 'Spirit Moves by Dave Douglas &amp; Brass Ecstasy', 'Live at Jazz Standard [8-​set] by Dave Douglas &amp; Keystone', 'Moonshine by Dave Douglas &amp; Keystone', 'Live at the Jazz Standard [12-set] by Dave Douglas Quintet', 'DD|50: Special Edition 50th Birthday Recordings by Dave Douglas', 'Keystone by Dave Douglas &amp; Keystone', 'Spark Of Being: Burst by Dave Douglas &amp; Keystone', 'Spark Of Being: Expand by Dave Douglas &amp; Keystone', 'Spark Of Being: Soundtrack by Dave Douglas &amp; Keystone' ]"
          },
          created_at: new Date('2017-07-20T13:44:00.000Z'),
          updated_at: new Date('2017-07-20T13:44:00.000Z')
        },
        {
          id: 45,
          user_id: 1,
          name: 'Pierre Boulez (composer, theorist, conductor), born 1925',
          color: '#30303B',
          picture: './img/musicians/pierreboulez.jpg',
          day_of: new Date ('1925-03-26'),
          is_annual: true,
          art_override: false,
          music_override: false,
          override_content: null,
          created_at: new Date('2017-07-20T13:44:00.000Z'),
          updated_at: new Date('2017-07-20T13:44:00.000Z')
        },
        {
          id: 46,
          user_id: 1,
          name: 'Marilyn Crispell (piano, improviser), born 1947',
          color: '#560408',
          picture: './img/musicians/marilyncrispell.jpg',
          day_of: new Date ('1947-03-30'),
          is_annual: true,
          art_override: false,
          music_override: true,
          override_content: {
            "sources": "[ 'bandcamp', 'bandcamp', 'bandcamp', 'bandcamp', 'bandcamp', 'bandcamp' ]",
            "src_strings": "[ 'https://bandcamp.com/EmbeddedPlayer/album=1669848992/size=large/bgcol=ffffff/linkcol=0687f5/tracklist=false/transparent=true/', 'https://bandcamp.com/EmbeddedPlayer/album=864535906/size=large/bgcol=ffffff/linkcol=0687f5/tracklist=false/transparent=true/', 'https://bandcamp.com/EmbeddedPlayer/album=3011883875/size=large/bgcol=ffffff/linkcol=0687f5/tracklist=false/transparent=true/', 'https://bandcamp.com/EmbeddedPlayer/album=3250405659/size=large/bgcol=ffffff/linkcol=0687f5/tracklist=false/transparent=true/', 'https://bandcamp.com/EmbeddedPlayer/album=1989500445/size=large/bgcol=ffffff/linkcol=0687f5/tracklist=false/transparent=true/', 'https://bandcamp.com/EmbeddedPlayer/album=2848298419/size=large/bgcol=ffffff/linkcol=0687f5/tracklist=false/transparent=true/' ]",
            "href_strings": "[ 'http://destination-out.bandcamp.com/album/pianosolo-a-concert-in-berlin', 'http://babel-label.bandcamp.com/album/parallel-moments', 'http://intaktrec.bandcamp.com/album/table-of-changes', 'http://intaktrec.bandcamp.com/album/affinities', 'http://ditzner.bandcamp.com/album/free-flight', 'http://gustafsson1.bandcamp.com/album/gryffgryffgryffs' ]",
            "a_strings": "[ 'Pianosolo — A Concert in Berlin by MARILYN CRISPELL', 'PARALLEL MOMENTS by RAYMOND MACDONALD &amp; MARILYN CRISPELL', 'Table of Changes by Marilyn Crispell – Gerry Hemingway', 'Affinities by Marilyn Crispell and Gerry Hemingway', 'free flight by MARILYN CRISPELL, ERWIN DITZNER, SEBASTIAN GRAMSS', 'Gryffgryffgryffs by Guy-Gustafsson-Strid Trio with Marilyn Crispell' ]"
          },
          created_at: new Date('2017-07-20T13:44:00.000Z'),
          updated_at: new Date('2017-07-20T13:44:00.000Z')
        },
        {
          id: 47,
          user_id: 1,
          name: 'René Descartes (philosopher, mathematician, scientist), born 1596',
          color: '#FAEBD6',
          picture: './img/maths/renedescartes.jpg',
          day_of: new Date ('1596-03-31'),
          is_annual: true,
          art_override: false,
          music_override: false,
          override_content: null,
          created_at: new Date('2017-07-20T13:44:00.000Z'),
          updated_at: new Date('2017-07-20T13:44:00.000Z')
        },
        {
          id: 48,
          user_id: 1,
          name: 'Alexandra Kollontai (communist revolutionary), born 1872',
          color: '#6D6C77',
          picture: './img/maths/alexandrakollontai.jpg',
          day_of: new Date ('1872-03-31'),
          is_annual: true,
          art_override: false,
          music_override: false,
          override_content: null,
          created_at: new Date('2017-07-20T13:44:00.000Z'),
          updated_at: new Date('2017-07-20T13:44:00.000Z')
        }
      ]);
    }).then(() => {
      return knex.raw("SELECT setval('observances_id_seq', (SELECT MAX(id) FROM observances));");
    });
};
